services:
  - type: web
    name: multilingual-sentiment-app
    env: python
    buildCommand: pip install -e .
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GEMINI_API_KEY
        sync: false  # This will be set manually in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production