services:
  - type: web
    name: multilingual-sentiment-app
    env: python
    python:
      version: 3.9.0  # Using Python 3.9 for better compatibility
    buildCommand: |
      python -m pip install --upgrade pip
      pip install setuptools wheel
      pip install -r requirements.txt --no-cache-dir
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false  # This will be set manually in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: true